# Generated by Django 5.1.1 on 2024-09-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_uploadedfile_delete_someothermodel"),
    ]

    operations = []
