# Generated by Django 5.1.1 on 2024-09-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_otp"),
    ]

    operations = []
