# Generated by Django 5.1.1 on 2024-09-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20240924_1331"),
    ]

    operations = []
