# Generated by Django 5.1.1 on 2024-09-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_auto_20240924_1434"),
    ]

    operations = []
