# Generated by Django 5.1.1 on 2024-09-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_auto_20240924_1638"),
    ]

    operations = []
