# Generated by Django 5.1.1 on 2024-09-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_auto_20240924_1729"),
    ]

    operations = []
