# Generated by Django 5.1.1 on 2024-09-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_auto_20240924_1816"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OTP",
        ),
    ]
