# Generated by Django 5.1.1 on 2024-09-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_otp"),
    ]

    operations = []
