# Generated by Django 5.1.1 on 2024-09-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_auto_20240924_2350"),
    ]

    operations = []
