# Generated by Django 5.1.1 on 2024-09-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_auto_20240925_0018"),
    ]

    operations = []
