# Generated by Django 5.1.1 on 2024-09-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_auto_20240925_1016"),
    ]

    operations = []
