# Generated by Django 5.1.1 on 2024-09-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_customuser_managers_alter_customuser_email_and_more"),
    ]

    operations = []
