# Generated by Django 5.1.1 on 2024-09-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_auto_20240925_1119"),
    ]

    operations = []
