# Generated by Django 5.1.1 on 2024-09-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_auto_20240925_1120"),
    ]

    operations = []
