# Generated by Django 5.1.1 on 2024-09-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_auto_20240925_1235"),
    ]

    operations = []
