# Generated by Django 5.1.1 on 2024-09-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_auto_20240925_1256"),
    ]

    operations = []
