# Generated by Django 5.1.1 on 2024-09-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_auto_20240925_1433"),
    ]

    operations = []
