# Generated by Django 5.1.1 on 2024-09-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_auto_20240925_1521"),
    ]

    operations = []
