# Generated by Django 5.1.1 on 2024-09-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_auto_20240925_1632"),
    ]

    operations = []
