# Generated by Django 5.1.1 on 2024-09-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_auto_20240925_1706"),
    ]

    operations = []
