# Generated by Django 5.1.1 on 2024-09-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_auto_20240925_1742"),
    ]

    operations = []
